version: '3.5'

networks:
  frontend:
    external:
      name: frontend

services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    build: .
    ports:
      - "81:8181"
      - "80:8080"
      - "443:4443"
    volumes:
      - "/docker/appdata/nginx-proxy-manager:/config:rw"

    networks:
      frontend:
        ipv4_address: 172.19.0.2

